services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
    networks:
      - app-network
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
    depends_on:
      - api
    networks:
      - app-network
networks:
  app-network:
    driver: bridge