FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY streamlit_app/ ./streamlit_app/
COPY src/ ./src/

EXPOSE 8000

CMD ["streamlit", "run", "streamlit_app/app.py", "--server.port=8000", "--server.address=0.0.0.0"]
