name: Mental Health ML CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/ --verbose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker build -t mental-health-ml-api -f Dockerfile.api .
          docker build -t mental-health-ml-streamlit -f Dockerfile.streamlit .

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 30
          curl -f http://localhost:8000/health || exit 1
          curl -f http://localhost:8501 || exit 1
          docker compose down
